# Generated by Django 6.0.3 on 2026-03-08 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrawingType",
            fields=[
                (
                    "drawing_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "drawing_types",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "image_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component_name", models.CharField(max_length=200)),
                ("image_binary", models.BinaryField()),
                ("content_hash", models.CharField(max_length=64)),
                ("width_px", models.IntegerField()),
                ("height_px", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drawing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="api.drawingtype",
                    ),
                ),
            ],
            options={
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="FittingPosition",
            fields=[
                (
                    "fitting_position_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("x_coordinate", models.DecimalField(decimal_places=3, max_digits=10)),
                ("y_coordinate", models.DecimalField(decimal_places=3, max_digits=10)),
                ("label_text", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitting_positions",
                        to="api.image",
                    ),
                ),
            ],
            options={
                "db_table": "fitting_positions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("image", "label_text"), name="uq_image_label_text"
                    )
                ],
            },
        ),
    ]
