# Generated by Django 6.0.3 on 2026-03-08 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "upload_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component_name", models.CharField(max_length=200)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("expected_checksum", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("uploading", "Uploading"),
                            ("verifying", "Verifying"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drawing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to="api.drawingtype",
                    ),
                ),
                (
                    "image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_session",
                        to="api.image",
                    ),
                ),
            ],
            options={
                "db_table": "image_uploads",
            },
        ),
        migrations.CreateModel(
            name="UploadChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.PositiveIntegerField()),
                ("data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="api.imageupload",
                    ),
                ),
            ],
            options={
                "db_table": "upload_chunks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("upload", "part_number"), name="uq_upload_part"
                    )
                ],
            },
        ),
    ]
