# Generated by Django 6.0.3 on 2026-03-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_add_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="uploader_identity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
