# Generated by Django 6.0.3 on 2026-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_imageupload_uploader_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
