# Generated by Django 6.0.3 on 2026-03-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_image_thumbnail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fittingposition',
            index=models.Index(fields=['image'], name='idx_fp_image_id'),
        ),
    ]
