# Generated by Django 6.0.3 on 2026-03-10 21:30

from django.db import migrations, models
from django.db.models.functions import Lower, Trim


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_add_fp_image_id_index"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                Lower(Trim("component_name")),
                name="uq_images_component_name_normalized",
            ),
        ),
    ]
