[mypy]
python_version = 3.13
plugins = mypy_django_plugin.main, mypy_drf_plugin.main
strict = True
warn_unreachable = True

[mypy-environ]
ignore_missing_imports = True

[mypy-cairosvg]
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings

[mypy-django_auth_ldap]
ignore_missing_imports = True

[mypy-django_auth_ldap.config]
ignore_missing_imports = True

[mypy-ldap3]
ignore_missing_imports = True